$primary_paletteKeyColor = a46385
$secondary_paletteKeyColor = 8c6f7c
$tertiary_paletteKeyColor = 9b6d51
$neutral_paletteKeyColor = 7f7478
$neutral_variant_paletteKeyColor = 827379
$background = 181115
$onBackground = eedfe3
$surface = 181115
$surfaceDim = 181115
$surfaceBright = 40373a
$surfaceContainerLowest = 130c0f
$surfaceContainerLow = 21191d
$surfaceContainer = 251d21
$surfaceContainerHigh = 30282b
$surfaceContainerHighest = 3b3236
$onSurface = eedfe3
$surfaceVariant = 504349
$onSurfaceVariant = d4c2c8
$inverseSurface = eedfe3
$inverseOnSurface = 372e32
$outline = 9c8d92
$outlineVariant = 504349
$shadow = 000000
$scrim = 000000
$surfaceTint = fcb0d6
$primary = fcb0d6
$onPrimary = 521d3c
$primaryContainer = 6c3453
$onPrimaryContainer = ffd8e9
$inversePrimary = 884b6b
$secondary = dfbdcc
$onSecondary = 402a35
$secondaryContainer = 5b424e
$onSecondaryContainer = fdd9e8
$tertiary = f3ba9b
$onTertiary = 4a2811
$tertiaryContainer = b88669
$onTertiaryContainer = 000000
$error = ffb4ab
$onError = 690005
$errorContainer = 93000a
$onErrorContainer = ffdad6
$primaryFixed = ffd8e9
$primaryFixedDim = fcb0d6
$onPrimaryFixed = 380726
$onPrimaryFixedVariant = 6c3453
$secondaryFixed = fdd9e8
$secondaryFixedDim = dfbdcc
$onSecondaryFixed = 291520
$onSecondaryFixedVariant = 58404b
$tertiaryFixed = ffdbc9
$tertiaryFixedDim = f3ba9b
$onTertiaryFixed = 311302
$onTertiaryFixedVariant = 643d25
$term0 = 353434
$term1 = ff46a1
$term2 = ffbabe
$term3 = ffdee2
$term4 = b3a2d5
$term5 = e590bb
$term6 = ffba93
$term7 = eed2d5
$term8 = b39ea1
$term9 = ff7eb3
$term10 = ffd3d4
$term11 = fff1f1
$term12 = babfdd
$term13 = f5a9cb
$term14 = ffd1c0
$term15 = ffffff
$rosewater = ffedf1
$flamingo = fad9e4
$pink = ffd0e7
$mauve = f9a6e0
$red = f895c4
$maroon = f0abc7
$peach = ffbbcd
$yellow = ffedee
$green = ffd8c5
$teal = dedcff
$sky = ebd1ff
$sapphire = eeb3f6
$blue = eda5e8
$lavender = f9b8ed
$klink = b170b5
$klinkSelection = b170b5
$kvisited = bf5ea2
$kvisitedSelection = c05ea1
$knegative = e4509a
$knegativeSelection = e44f99
$kneutral = ff83ab
$kneutralSelection = ff83ab
$kpositive = fd8c2a
$kpositiveSelection = fd8c2a
$text = eedfe3
$subtext1 = d4c2c8
$subtext0 = 9c8d92
$overlay2 = 887a7f
$overlay1 = 74676c
$overlay0 = 62565b
$surface2 = 50454a
$surface1 = 3e3539
$surface0 = 2b2327
$base = 181115
$mantle = 181115
$crust = 171014
$success = B5CCBA
$onSuccess = 213528
$successContainer = 374B3E
$onSuccessContainer = D1E9D6
