$background = 181214
$onBackground = ecdfe2
$surface = 181214
$surfaceDim = 181214
$surfaceBright = 3f3739
$surfaceContainerLowest = 120d0e
$surfaceContainerLow = 201a1c
$surfaceContainer = 241e20
$surfaceContainerHigh = 2f282a
$surfaceContainerHighest = 3a3335
$onSurface = ecdfe2
$surfaceVariant = 514347
$onSurfaceVariant = d6c1c6
$outline = 9e8c91
$outlineVariant = 514347
$inverseSurface = ecdfe2
$inverseOnSurface = 362f30
$shadow = 000000
$scrim = 000000
$surfaceTint = ffb0cc
$primary = ffb0cc
$primaryDim = ffacc9
$onPrimary = 541c35
$primaryContainer = d386a2
$onPrimaryContainer = 592039
$inversePrimary = 8b4963
$primaryFixed = ffd9e4
$primaryFixedDim = ffb0cc
$onPrimaryFixed = 3a061f
$onPrimaryFixedVariant = 70324b
$secondary = e6bbc8
$secondaryDim = f1c6d3
$onSecondary = 442832
$secondaryContainer = 5d3e49
$onSecondaryContainer = d3aab7
$secondaryFixed = ffd9e4
$secondaryFixedDim = e6bbc8
$onSecondaryFixed = 2c141d
$onSecondaryFixedVariant = 5d3e49
$tertiary = ffb68e
$tertiaryDim = feab7c
$onTertiary = 542200
$tertiaryContainer = d78a5e
$onTertiaryContainer = 592501
$tertiaryFixed = ffdbca
$tertiaryFixedDim = ffb68e
$onTertiaryFixed = 331200
$onTertiaryFixedVariant = 703712
$error = ffb4ab
$errorDim = ff554a
$onError = 690005
$errorContainer = 93000a
$onErrorContainer = ffdad6
$primaryPaletteKeyColor = a8617c
$secondaryPaletteKeyColor = 916d79
$tertiaryPaletteKeyColor = d78a5e
$neutralPaletteKeyColor = 7f7577
$neutralVariantPaletteKeyColor = 847378
$errorPaletteKeyColor = de3730
$primary_paletteKeyColor = a8617c
$secondary_paletteKeyColor = 916d79
$tertiary_paletteKeyColor = d78a5e
$neutral_paletteKeyColor = 7f7577
$neutral_variant_paletteKeyColor = 847378
$term0 = 353434
$term1 = ff4b8d
$term2 = ffbbb8
$term3 = ffdedf
$term4 = b3a2d5
$term5 = e990b2
$term6 = ffba93
$term7 = eed1d2
$term8 = b39e9f
$term9 = ff80a5
$term10 = ffd3d1
$term11 = fff1f1
$term12 = dcbc93
$term13 = f8a8c3
$term14 = ffd1c0
$term15 = ffffff
$rosewater = ffedef
$flamingo = fcd9e1
$pink = ffd1e2
$mauve = ffa4d7
$red = fc95b9
$maroon = f3aac0
$peach = ffbcc6
$yellow = ffeded
$green = ffd8c5
$teal = dedcff
$sky = ebd1ff
$sapphire = f2b2f2
$blue = f3a3e0
$lavender = feb7e6
$klink = b66eae
$klinkSelection = b76ead
$kvisited = c45d97
$kvisitedSelection = c45d96
$knegative = e84f8a
$knegativeSelection = e84f88
$kneutral = ff859f
$kneutralSelection = ff859d
$kpositive = fd8c2a
$kpositiveSelection = fd8c2a
$text = ecdfe2
$subtext1 = d6c1c6
$subtext0 = 9e8c91
$overlay2 = 8a7a7e
$overlay1 = 75676b
$overlay0 = 63565a
$surface2 = 504649
$surface1 = 3e3538
$surface0 = 2b2326
$base = 181214
$mantle = 181214
$crust = 171113
$success = B5CCBA
$onSuccess = 213528
$successContainer = 374B3E
$onSuccessContainer = D1E9D6
