# Reloading tmux conf
unbind r
bind r source-file ~/.config/tmux/tmux.conf

# Set true color
set-option -sa terminal-overrides ",xterm*:Tc"
set -g default-terminal "tmux-256color"
set -g mouse on

# Set prefix
unbind C-b
set -g prefix C-space
bind C-space send-prefix

# Mouse support
set -g mouse on

# Ctrl Alt vim keys to switch windows
bind -n C-M-h previous-window
bind -n C-M-l next-window

# Start windows number at 1
set -g base-index 1
set -g pane-base-index 1
set-window-option -g pane-base-index 1
set-option -g renumber-windows on

# Tmux aesthetic config
set-option -g status-position top
# set -g status-left ''
# set -g status-right ''
# set -g @curr_wind_container 'colour9'
# set -g @container 'colour16'
# set -g @wind_text 'colour0'
# set -g @prefix_active 'colour1'

# setw -g window-status-current-format \
# '#{?#{==:#{window_index},1},#[bg=default],#[bg=#{@container}]}\
# #{?#{==:#{client_prefix},1},#[fg=#{@prefix_active}],#[fg=#{@curr_wind_container}]}\
# #[fg=#{@wind_text}]\
# #{?#{==:#{client_prefix},1},#[bg=#{@prefix_active}],#[bg=#{@curr_wind_container}]} \
# #I #W #{?#{==:#{last_window_index},#{window_index}},#[bg=default],#[bg=#{@container}]}\
# #{?#{==:#{client_prefix},1},#[fg=#{@prefix_active}],#[fg=#{@curr_wind_container}]}'
#
# setw -g window-status-format '#[fg=#{@container}]#{?#{==:#{window_index},1},,}#[fg=#{@wind_text},bg=#{@container}] #I #W #[fg=#{@container}]#[bg=default]#{?#{==:#{last_window_index},#{window_index}},,}'
# setw -g window-status-separator ""

# Plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'tmux-plugins/tmux-yank'
set -g @plugin 'catppuccin/tmux#v2.3.0'

# Set vi-mode
setw -g mode-keys vi

# Keybindings
# Copy mode
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi C-v send-keys -X rectangle-toggle
bind-key -T copy-mode-vi y send-keys -X copy-selection-and-cancel

# Changing window position
bind-key h swap-window -t -1 \; previous-window
bind-key l swap-window -t +1 \; next-window

# Open panes in current dir
bind '"' split-window -v -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"
bind c new-window -c "#{pane_current_path}"

set -g @catppuccin_flavor "mocha"
set -g @catppuccin_window_status_style "rounded"
set -gq @catppuccin_window_number_color "#{@thm_blue}"
set -g @catppuccin_window_current_number_color "#{?client_prefix,#{@thm_red},#{@thm_mauve}}"

run '~/.tmux/plugins/tpm/tpm'

set -g status-right-length 100
set -g status-left-length 100
set -g status-left ""
set -g status-right "#{E:@catppuccin_status_application}"
set -g status-bg default
set -g status-style bg=default
