input {
    kb_layout = us
    numlock_by_default = false
    repeat_delay = 250
    repeat_rate = 35

    focus_on_close = 1
    sensitivity = -0.4

    touchpad {
        natural_scroll = true
        disable_while_typing = $touchpadDisableTyping
        scroll_factor = $touchpadScrollFactor
    }
}

binds {
    scroll_event_delay = 0
    # allow_workspace_cycles = true
}
# binds:workspace_back_and_forth = true

cursor {
    hotspot_padding = 1
}

device {
    name = logi-m240-mouse
    sensitivity = $extMouseSensitivity
}

device {
    name = 04ca00a0:00-04ca:00b1-touchpad
    accel_profile = flat
    sensitivity = 0.2
}
