# -----------------
# MOVE THIS FILE TO /etc/keyd/
# -----------------
[ids]

*

[main]

# Maps capslock to escape when pressed and control when held.
capslock = overload(control, esc)
leftcontrol = overload(control, esc)
# [ = backspace
# ] = delete
# rightalt = layer(symbols)
# rightcontrol = layer(nav)

[symbols]
q = 1
w = 2
e = 3
r = 4
t = 5
y = 6
u = 7
i = 8
o = 9
p = 0
a = !
s = @
d = #
f = $
g = %
h = ^
j = &
k = *
l = (
; = )
z = -
x = _
c = =
v = +
b = [
n = ]
m = {
, = }
. = `
/ = ~
leftalt = \
space = |
enter = print

[nav]
h = left
j = down
k = up
l = right
